name: tools signin

on: 
  push: 
    branches: 
      - master
  schedule: 
    - cron: '0 21 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: signin
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ANSWER: ${{ secrets.ANSWER }}
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python Auto_tools_signin.py
